### PR TITLE
Add better GUI

### PR DESCRIPTION
**Pull request by im-coder-lg**
Yup - I tested the entire GUI. Theme files are here, so you just need to copy `test.py`'s contents.
Still incomplete, if I could figure this out, maybe I'll add the multiple windows too.

### CODE REVIEW

**Comment by not-nef** [comment]
@im-coder-lg The next thing you should do is get the download link of the latest msi with the `api_response.json()` function!

**Comment by im-coder-lg** [comment]
I think I figured it out, check this out: https://api.github.com/repos/TimerX-App/TimerX/releases/assets/52968592
We could use the same method to get the `browser_download_url` variable or whatever it is. Then I will try wrapping it around in a `Class` to make multiple windows. I have tried this before but it failed _horribly_ so I hope it gets right this time!
The only problem with the URL is that you need an 8-digit code to get the release binary URL, meaning we have to bump them _after_ the release is out.

**Comment by im-coder-lg** [comment]
@not-nef is this right?

**Comment by sumeshir26** [comment]
Good work, but make sure to not spend too much time making a nice gui, since all this needs to be completely recoded over on the main repo. This repo is just to test the system

**Comment by im-coder-lg** [comment]
Maybe we'll try adding TimerX here _with_ the update window. It will open only when there are updates, that's what puzzles me though. How do we do that?

**Comment by im-coder-lg** [comment]
I'll try testing this.

**Comment by not-nef** [comment]
> @not-nef is this right?

No, because this script would always download the same msi, no matter what release we are at. You have to get the msi download link from `api.github.com/repos/TimerX-App/TimerX/releases/latest`

**Comment by not-nef** [comment]
And also this would open a webbrowser right? Maybe we find a way to download the file with some module?

**Comment by im-coder-lg** [comment]
That is literally what I did! I sent a request but noticed that you need to download a single file. There are multiple  URLs for one variable. That's why I did that.

**Comment by im-coder-lg** [comment]
> And also this would open a webbrowser right? Maybe we find a way to download the file with some module?

Then it would save the executable to only one location. That is kind of problematic with low memory computers, but if the user downloaded it, they could not only find the file but also share or do anything with it. Ease of use.

**Comment by im-coder-lg** [comment]
> No, because this script would always download the same msi

If you bump the versions every release, it won't.

**Comment by not-nef** [comment]
> Then it would save the executable to only one location. That is kind of problematic with low memory computers, but if the user downloaded it, they could not only find the file but also share or do anything with it. Ease of use.

Well if we launch the msi after its downloaded, the user doesnt need to do anything at all with it and just has to go through the installation process. Thats more user-friendly in my opinon.

**Comment by not-nef** [comment]
> If you bump the versions every release, it won't.

What do you mean?

**Comment by im-coder-lg** [comment]
You have to bump releases here since we use a custom variable. Once it's on main.py, you must bump `ver` before every release. That's how you stop the error from loading. So, if we bump that, why not bump even the URL? Or maybe I'll link the version to the URL so it opens the same URL. Anyway, we use fixed workflows so the name is the same.

**Comment by not-nef** [comment]
I dont get it, but what matters is that it works

**Comment by im-coder-lg** [comment]
It does! Wait I have one more thing to do, will do it soon.

**Comment by not-nef** [comment]
Just tell me i have some free time rn

**Comment by im-coder-lg** [comment]
I will do that last thing, but I need some help. Can you tell me how to add multiple Tkinter windows? It's puzzling and I failed horribly in this, can you tell how?

**Comment by im-coder-lg** [comment]
Yikes, GitHub Mobile glitched!

**Comment by not-nef** [comment]
> I will do that last thing, but I need some help. Can you tell me how to add multiple Tkinter windows? It's puzzling and I failed horribly in this, can you tell how?

Instead of adding another tkinter.tk() use tkinter.toplevel() for multiple windows!

**Comment by not-nef** [comment]
Does it work @im-coder-lg ?

**Comment by im-coder-lg** [comment]
It works as I expected, I will commit it now.

**Comment by im-coder-lg** [comment]
Actually, it sorta doesn't but does. The window size is not what I wanted but the labels seem to fit. I don't know, is this a problem on my part

**Comment by im-coder-lg** [comment]
@sumeshir26 is this fine?

**Review by not-nef — APPROVED** [review]
epic

**Comment by sumeshir26** [comment]
You can merge!

**Review by sumeshir26 — APPROVED** [review]

**Comment by im-coder-lg** [comment]
Merging!

**Pull request merged**
